config/routes.rb
Rails.application.routes.draw do
  # resources :pieces
  # resources :museums
  # resources :artists
  get '/museums/open', to: 'museums#open'
  match '/auth/:provider/callback', to: 'session#github_login', via: [:get, :post]
  resources :artists, except: [:index, :destroy] do
    resources :pieces, only: [:show, :index]
  end
  resources :museums, except: [:edit, :update, :destroy] do
    resources :pieces, only: [:show, :index, :new, :create]
  end
  resources :pieces, only: [:edit, :update, :destroy]
  root 'static#home'
  get '/signin', to: 'session#new', as: 'signin'
  post '/session', to: 'session#create', as: 'session'
  delete '/session/', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_secure_password
    has_many :pieces
	has_many :museums, through: :pieces

    validates :username, presence: true, uniqueness: true
    validates_presence_of [:name, :hometown]
    
    scope :non_github_login, -> { where(github_login: false) }
end

app/models/museum.rb
class Museum < ApplicationRecord
    has_many :pieces
	has_many :artists, through: :pieces
    scope :open_status, -> { where(open_status: true) }

    scope :ordered_list, -> { order(name: :asc) }

    validates_presence_of [:name, :location]
end

app/models/piece.rb
class Piece < ApplicationRecord
    belongs_to :museum
	belongs_to :artist

    validates_presence_of [:name, :year_created] 

    def make_art
        if self.artist.pieces.count == 1
            "Congrats, you are now an artist."
        elsif self.artist.pieces.count <= 1 && self.artist.pieces.count >= 5
            "Another masterpiece created. You are really VanGogh-ing somewhere."
        elsif  self.artist.pieces.count < 5
            "Another masterpiece created. You are the pinacle of artistic abilities."
        end
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :logged_in
    helper_method :current_user
  
    private
  
    def logged_in
      redirect_to '/' unless user_auth
    end
  
    def user_auth
      !!current_user
    end
  
    def current_user
      Artist.find_by(id: session[:artist_id])
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    skip_before_action :logged_in, only: [:new, :create]

    def new
        @artist = Artist.new
    end

    def create
        (@artist = Artist.create(artist_params))
        if @artist.id
            session[:artist_id] = @artist.id
            redirect_to artist_path(@artist)
        else
            render 'new'
        end
    end

    def show
        @artist = Artist.find_by(id: params[:id])
    end

    def edit
        @artist = Artist.find_by(id: params[:id])
    end

    def update
        @artist = Artist.find_by_id(params[:id])
        if @artist.update(name: params[:artist][:name], username: params[:artist][:username], hometown: params[:artist][:hometown])
            if params[:artist][:password] != ""
                @artist.update(password: params[:artist][:password])
            end
            message = "Profile Updated"
            redirect_to artist_path(@artist), flash: {message: message}
        else
            render 'edit'
        end
    end

    private
  
    def artist_params
      params.require(:artist).permit(:username, :name, :hometown, :password)
    end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController

    
    def index
        @museums = Museum.ordered_list
    end

    def new
        @museum = Museum.new
    end

    def create
        @museum = Museum.new(museum_params)
        if @museum.save
            redirect_to museum_path(@museum)
        else
            render 'new'
        end

    end

    def show
        @museum = Museum.find_by(id: params[:id])
        @piece = @museum.pieces.build(artist_id: current_user.id)
    end

    def open
        @museums = Museum.open_status
    end

    private
  
    def museum_params
      params.require(:museum).permit(:name, :location)
    end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController

    
    def index
        @pieces = Piece.all
    end

    def new
        @piece = Piece.new
    end

    def create
        piece = Piece.create(piece_params)
        message = piece.make_art
        redirect_to artist_path(piece.artist), flash: {message: message}
    end

    def show
    end

    def edit
        @piece = Piece.find_by_id(params[:id])
    end

    def update
        @piece = Piece.find_by_id(params[:id])
        if @piece.update(piece_params)
            redirect_to museum_path(@piece.museum)
        else
            render 'edit'
        end
    end

    def destroy
        piece = Piece.find_by_id(params[:id])
        if current_user.id == piece.artist_id
            name = piece.name
            piece.destroy
            message = "#{name} Successfully Removed"
            redirect_to artist_path(piece.artist_id), flash: {message: message}
        end
    end

    private
  
    def piece_params
      params.require(:piece).permit(:artist_id, :museum_id, :name, :year_created, :image, :image_description)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    skip_before_action :logged_in
    skip_before_action :verify_authenticity_token, only: :create
  
    def new
      @artist = Artist.new
      @all_artists = Artist.non_github_login
    end

    def create
        @artist = Artist.find_by(username: params[:artist][:username])
        if @artist && @artist.authenticate(params[:password])
          session[:artist_id] = @artist.id
          redirect_to artist_path(@artist)
        elsif @artist
          @errors = ["Invalid Password"]
          @all_artists = Artist.non_github_login
          render :new
        else
          @errors = ["Invalid Username"]
          @all_artists = Artist.non_github_login
          render :new
        end
    end

    def github_login
      @artist = Artist.find_or_create_by(username: self.request.env['omniauth.auth']['info']['nickname']) do |a|
        session[:omniauth_data] = request.env['omniauth.auth']
        session[:name] = request.env['omniauth.auth']['info']['name']
        a.password = SecureRandom.hex
        a.name = session[:name]
        a.hometown = session[:omniauth_data][:extra][:raw_info][:location]
        a.github_login = true
      end
      if @artist.save
        session[:artist_id] = @artist.id
        redirect_to artist_path(@artist)
      else
        redirect_to signin_path
      end
    end

    def destroy
      # session.delete("artist_id")
      reset_session
      redirect_to root_path
    end

  end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    skip_before_action :logged_in
  
    def home
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
    <% if @artist.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :username, "Username" %>
    <br>
    <%= f.text_field :username %>
    <br>
    <%= f.label :hometown, "What is your Hometown?" %>
    <br>
    <%= f.text_field :hometown %>
    <br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>

    <br/>
    <%= f.submit  %>
<% end %>

app/views/artists/edit.html.erb
<%= render 'form' %> 

app/views/artists/new.html.erb
<%= render 'form' %> 

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<% if flash[:message] %>
  <div class="center alert">
    <h3><%= flash[:message] %></h3>
  </div>
<% end %>

<p><strong>Name:</strong> <%= @artist.name %></p>
<p><strong>Hometown:</strong> <%= @artist.hometown %></p>
<p><strong>Username:</strong>  <%= @artist.username %></p>
<p><%= link_to 'Edit Profile', edit_artist_path(@artist.id) %></p>
<p><%= link_to 'See Masterpieces', artist_pieces_path(@artist.id) %></p>
<p><%= link_to 'See Museums', museums_path %></p><br><br>

<% if @artist.pieces.any? %>
  <h4>Your Art is located in the following Museums or Galleries:</h4> 
  <% @artist.museums.each do |museum| %>
  <%= render partial: 'museums/museum', locals: {museum: museum} %>
  <% end %>
<% else %>
  <h4>Submit a new Piece to a Museum or Gallery:</h4>
  <%= link_to 'New Submission', museums_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsArtistsMuseumsPieces</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if !current_user %>
          <a class="navbar-brand" href="<%= new_artist_path %>"/>Sign Up</a> 
          <%= link_to "Log in", signin_path, class:"navbar-brand" %>
          <%= link_to 'Sign in with GitHub', '/auth/github'%>
        <% else %>
          <%= link_to "#{current_user.name}'s profile", artist_path(current_user), class:"navbar-brand"%>
          <%= link_to "Log Out", session_path, class:"navbar-brand",method:'delete' %>
          <%= link_to "Submit New Artwork to a Museum or Gallery", museums_path, class:"navbar-brand" %>
        <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/museums/_form.html.erb
<%= form_for @museum do |f| %>
    <%= f.label :name %><br>
    <%=f.text_field :name %> <br>

    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <br>
    <%= f.submit class: "btn btn-primary" %> 
<% end %> 

app/views/museums/_museum.html.erb
<strong>Name: </strong><%= museum.name %>
<strong>Location: </strong><%= museum.location %>
<strong>Pieces in Collection: </strong><%= museum.pieces.count %>
<strong>Total Number of Artists: </strong> <%= museum.artists.count %>
<strong>Currently: </strong><%= museum.open_status ? "Open" : "Closed" %>
<%= link_to "View or Submit New Art", museum_path(museum) %> <br>

app/views/museums/index.html.erb
<h1>List of Museums</h1>

  <% @museums.each do |museum| %>
    <%= render partial: 'museum', locals: {museum: museum} %>
  <%end%>

  <br>

  <% if @artist %>
  <p>
    <%= link_to "Back to profile", artist_path(@artist), {:class => "btn btn-primary"} %>
  </p>
<% else %>
  <p><%= link_to 'Open New Museum', new_museum_path %></p>
<% end %>

app/views/museums/new.html.erb
<h1>New Museum</h1>
<%= render 'form' %>

app/views/museums/open.html.erb
<h1>Museums Currently Open</h1>
<% @museums.each do |museum| %>
    <%= render partial: 'museum', locals: {museum: museum} %>
<%end%>

app/views/museums/show.html.erb
<%= render partial: 'museum', locals: {museum: @museum} %>
    
    <% if @museum.open_status == true %>
        <%= form_for @piece, url: museum_pieces_path(@museum.id) do |f| %>
            <%= f.hidden_field :artist_id %><br />
            <%= f.hidden_field :museum_id %><br />
            <%= f.label :name %>
            <%= f.text_field :name %>
            <%= f.label :year_created %>
            <%= f.text_field :year_created %>
            <%= f.label :image_url %>
            <%= f.text_field :image %>
            <%= f.label :image_description %>
            <%= f.text_field :image_description %>
            <%= f.submit "Submit a new Piece to this Museum", class:"btn btn-light" %>
        <% end %>
    <% end %>

    
        <% @museum.pieces.each do |piece| %>
            <% if piece.id %>
                <h4><%= piece.name %> - <%= piece.year_created %></h4>

                <% if piece.image %>
                    <img src="<%= piece.image %>" class="img-thumbnail" width="200" height="200" alt="<%= piece.image_description %>">
                <% end %>
                <p> created by <%= piece.artist.name %></p><br><br>
                <% if piece.artist_id == current_user.id %>
                    <%= link_to "Edit This Piece", edit_piece_path(piece) %>
                <% end %>
            <% end %>
        <% end %>

app/views/pieces/edit.html.erb
<% if @piece.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @piece.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<%= form_for @piece do |f| %>
    <%= f.label :name %><br>
    <%=f.text_field :name %> <br>

    <%= f.label :year_created %><br>
    <%= f.text_field :year_created %><br>

    <%= f.label :image %><br>
    <%= f.text_field :image %><br>

    <%= f.label :image_description %><br>
    <%= f.text_field :image_description %><br>
    <br>
    <%= f.submit class: "btn btn-primary" %> 
<% end %> 

<p><%= link_to 'Remove From Museum', piece_path(@piece), method:'delete' %></p>

app/views/pieces/index.html.erb
<h1>Your Masterpieces</h1>
<% artist = Artist.find_by_id(params[:artist_id]) %>
<% artist.pieces.each do |piece| %>
    <%=piece.name%><br>
    <%=piece.year_created%><br>
    <img src="<%= piece.image %>" class="img-thumbnail" width="200" height="200" alt="<%= piece.image_description %>"><br>
    <%= piece.image_description %><br>
<%end%>
<h4>Submit a new Piece to a Museum or Gallery:</h4>
  <%= link_to 'New Submission', museums_path %>

app/views/session/new.html.erb
<%= form_tag('/session', method: :post) do %>
    <%= label_tag(:username, "Your username:") %>
    <%= collection_select(:artist, :username, @all_artists, :username, :username, prompt: "Please select your username from this dropdown") %>
    <%= label_tag(:password, "Your password:") %>
    <%= password_field_tag(:password, nil) %>
 
    <%= submit_tag("Sign In") %>
<% end %> 